### PR TITLE
fix: skins of NPCs would not get applied properly

### LINKED ISSUE #201: Support skin from properties (priority)
https://discord.com/channels/413438066984747026/815363216947150879/1283501914415304789

### PR DESCRIPTION
**Pull request by Phoenix616**
### **User description**
This fixes that skin data wasn't read from the player info packet properly (at least not in 1.21.4) which is required to have skins working with plugins that add NPCs with fake players like Citizens.

The change also fixes that players/NPCs with the same apparent name would use the same skin as they were cached by username not by UUID.

___

### **PR Type**
Bug fix, Enhancement

___

### **Description**
- Fixed NPC skins not applying correctly by using UUID-based caching.

- Updated `updatePlayerSkin` to use UUID instead of username for skin management.

- Improved handling of player texture properties in `player_info` packets.

- Enhanced entity skin update logic to avoid conflicts with duplicate usernames.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>main.ts</strong><dd><code>Update `updatePlayerSkin` call to use UUID</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

prismarine-viewer/examples/scenes/main.ts

<li>Updated <code>updatePlayerSkin</code> call to include UUID parameter.<br> <li> Adjusted function call to align with new UUID-based caching.

</details>

  </td>
  <td><a href="https://github.com/zardoy/minecraft-web-client/pull/265/files#diff-62546698608e4d7b6842f809bea25b242656a334f6e79b12bb9db7ab2ae7a84a">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>entities.ts</strong><dd><code>Refactor skin caching and updates to use UUID</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

prismarine-viewer/viewer/lib/entities.ts

<li>Replaced username-based skin caching with UUID-based caching.<br> <li> Modified <code>updatePlayerSkin</code> to accept UUID for skin updates.<br> <li> Adjusted logic to fetch skins using UUID instead of username.<br> <li> Updated entity creation to use UUID for skin updates.

</details>

  </td>
  <td><a href="https://github.com/zardoy/minecraft-web-client/pull/265/files#diff-ac90a590e52054eac7ddf6f1a261260cece5fe3ac3f830e07f37cee96f574d06">+10/-9</a>&nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>entities.ts</strong><dd><code>Enhance `player_info` packet handling and skin updates</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/entities.ts

<li>Improved parsing of <code>player_info</code> packets for texture properties.<br> <li> Added fallback logic for missing texture properties in packets.<br> <li> Updated skin update logic to use UUID and handle missing data <br>gracefully.<br> <li> Fixed entity matching by UUID for skin updates.

</details>

  </td>
  <td><a href="https://github.com/zardoy/minecraft-web-client/pull/265/files#diff-fbd8e1205a6f8147097a9d9aab61b2a3ce28692d3e8bd2831b17022520fd7f81">+8/-4</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> <details> <summary>  Need help?</summary><li>Type <code>/help how to ...</code> in the comments thread for any questions about Qodo Merge usage.</li><li>Check out the <a href="https://qodo-merge-docs.qodo.ai/usage-guide/">documentation</a> for more information.</li></details>

### CODE REVIEW

**Comment by zardoy** [comment]
Yeah it seems it was changed. Anyway I see the build failing, definitely the type of entity metadata must be changed from string to string | number | boolean , though it should be okay to cast it in some places in the code. Also will try to do it myself if I have time

File: prismarine-viewer/viewer/lib/entities.ts [hunk 1]
```diff
@@ -879,15 +879,38 @@ function addArmorModel (entityMesh: THREE.Object3D, slotType: string, item: Item
...
+  let texturePath
+  const isPlayerHead = slotType === 'head' && item.name === 'player_head'
+  if (isPlayerHead) {
     removeArmorModel(entityMesh, slotType)
-    return
+    if (item.nbt) {
+      const itemNbt = nbt.simplify(item.nbt)
+      try {
+        let textureData
+        if (itemNbt.SkullOwner) {
```
Comment (zardoy) [inline prismarine-viewer/viewer/lib/entities.ts:890]: 👏  good catch

**Comment by zardoy** [comment]
i think its worth supporting fetching skin for heads from API just like we do for regular skins (https://github.com/zardoy/minecraft-web-client/issues/32) there are common patterns when map-making like using special names that give texture of specific block like chest

**Comment by Phoenix616** [comment]
> i think its worth supporting fetching skin for heads from API just like we do for regular skins (https://github.com/zardoy/minecraft-web-client/issues/32) there are common patterns when map-making like using special names that give texture of specific block like chest

All of those should be supported via this method. I'm not really aware of anyone using a different way.
