### PR TITLE
fix reset onFire state on respawn

### LINKED ISSUE #500: First person on fire effect doesn't go away
On play.mcraft.dun

### PR DESCRIPTION
**Pull request by Abu1982**
## Summary
Fixes #500

The first-person fire overlay effect persists indefinitely because the `onFire` reactive state is never reset on `respawn` or `end` events.

## Root Cause

In `src/entities.ts`, the `respawn` and `end` event handlers clear the `onFireTimeout` timer but do **not** reset `appViewer.playerState.reactive.onFire = false`. This means:

1. Player catches fire -> `onFire` set to `true` via `entity_metadata` or `entity_status`
2. Player dies and respawns -> timeout cleared, but `onFire` stays `true`
3. `FireRenderer.tsx` keeps rendering the fire overlay forever

## Fix

- Reset `onFire = false` in both `respawn` and `end` handlers
- Set `onFireTimeout = undefined` after clearing to prevent stale references
- Remove unused `wasOnFire` variable in `handleEntityMetadata`

## Summary by CodeRabbit

* **Bug Fixes**
  * Fire state now reliably resets during respawn and end events, preventing stuck "on fire" visuals.
  * Timed fire effects now clear cleanly to avoid lingering or duplicated on-fire displays.
  * On-fire status updates only occur when the state actually changes, reducing unnecessary visual updates.

### CODE REVIEW

File: src/entities.ts [hunk 1]
```diff
@@ -335,12 +339,16 @@ const ENTITY_FLAGS = {
 let onFireTimeout: NodeJS.Timeout | undefined
 const updateEntityStates = (entityId: number, onFire: boolean, timeout?: boolean) => {
   if (entityId !== bot.entity.id) return
-  appViewer.playerState.reactive.onFire = onFire
+  if (appViewer.playerState.reactive.onFire !== onFire) {
+    appViewer.playerState.reactive.onFire = onFire
```
Comment (zardoy) [inline src/entities.ts]: whats the purpose of this code block change

File: src/entities.ts [hunk 2]
```diff
@@ -141,13 +141,17 @@ customEvents.on('gameLoaded', () => {
   bot.on('end', () => {
     if (onFireTimeout) {
       clearTimeout(onFireTimeout)
+      onFireTimeout = undefined
     }
+    appViewer.playerState.reactive.onFire = false
```
Comment (zardoy) [inline src/entities.ts]: no need to add it there since new players tate is created on each server connect anyway

**Review by zardoy — CHANGES_REQUESTED** [review]
overwall much easier then i expected, hope it you tested it and it works:)

File: src/entities.ts (hunk 2 above)
Comment (Abu1982) [reply src/entities.ts]: Removed  only keeping the timeout cleanup in the end handler now.

File: src/entities.ts (hunk 1 above)
Comment (Abu1982) [reply src/entities.ts]: Removed the conditional wrapper, back to direct assignment. It was an unnecessary optimization attempt.

**Comment by zardoy** [comment]
ok nice

**Comment by Abu1982** [comment]
Thanks for the review! I've pushed a fix addressing the feedback  added a conditional check in updateEntityStates to avoid unnecessary Valtio subscriber notifications (consistent with handleEntityMetadata). I tested the fire overlay behavior: it correctly clears on respawn and disconnect, and the timeout-based auto-clear still works as expected.

**Comment by zardoy** [comment]
Please note that not all ai reviews are always correct, that comment was misleading. All experienced contributes who worked with react know about primitive compare mechanism and it already does it internally. I know it won't change runtime and not a big deal there but can you still revert that unnecessary check change to avoid potential confusion for future code contributors
